<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="3" time="0.118" timestamp="2024-10-19T13:28:18.775028" hostname="ZCSU016-ZL"><testcase classname="txt_Demo.test_pytestdemo" name="test_sample_one" time="0.001"><failure message="AssertionError: a is not equal to b&#10;assert 2 == 4">def test_sample_one():
        print("inside sample one")
        a=2
        b=4
&gt;       assert a==b,"a is not equal to b"
E       AssertionError: a is not equal to b
E       assert 2 == 4

txt_Demo\test_pytestdemo.py:7: AssertionError</failure></testcase><testcase classname="txt_Demo.test_pytestdemo" name="test_sample_two" time="0.001" /><testcase classname="txt_Demo.test_pytestdemo" name="test_sample_three" time="0.000" /></testsuite></testsuites>